// USERS TYPES
export const SET_ERRORS = 'SET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// PROFILES TYPES
export const SET_PROFILE = 'SET_PROFILE'
export const SET_PROFILES = 'SET_PROFILES'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
